#!/usr/bin/env python3

import sys
import subprocess

inputs = sys.argv

command = inputs[1]

try:
    if (command == "help"):
        print("[Python CMD] Available commands are: build and devrun")
    elif (command == "build"):
        print("[Python CMD]  Project is building.")
        subprocess.run(["dotnet", "build", "Catalog.sln"])
    elif (command == "devrun"):
        print("[Python CMD]  Project is running on Development ENV.")
        subprocess.run(["dotnet", "run", "--project", "WebApi/WebApi.csproj", "--verbosity", "m"])
    # elif (command == "test"):
    #     print("[Python CMD]  Project is now being tested.")
    #     subprocess.run(["dotnet", "test", "src/Tests"])
    else:
        print("[Python CMD]  Didn't Match Anything.")
except KeyboardInterrupt:
    print("[Python CMD] Program interrupted.")
