version: "3.1"

services:
    mongo:
        image: mongo:latest
        container_name: test_mongo
        restart: always
        ports:
            - 27017:27017
        # environment:
        #     MONGO_INITDB_ROOT_USERNAME: user
        #     MONGO_INITDB_ROOT_PASSWORD: pass
        volumes:
            - ~/.docker/test-mongo/:/data/db
